# Generated by Django 2.0 on 2018-11-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_auto_20180909_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainform',
            name='dustbin',
            field=models.CharField(choices=[('Sadar', 'Sadar'), ('Russell', 'Russell'), ('Reliance', 'Reliance'), ('IIITDM', 'IIITDM')], max_length=255),
        ),
    ]
